[package]
name = "wallpaper_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
noise = { version =  "0.8.2", features = ["images"] }
image = "0.24.9"
rand = "0.8.5"
rayon = "1.9"
indicatif = { version = "0.17.7", features = ["rayon"] }